apiVersion: v1
kind: Service
metadata:
  name: the-frontend
spec:
  type: NodePort
  selector:
    app: workshop-frontend-app
    type: pod
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 80
    nodePort: 32080
