apiVersion: v1
kind: Service
metadata:
  name: the-backend
spec:
  type: NodePort
  selector:
    app: workshop-backend-app
    type: pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32000
